import React,{useCallback,useEffect,useMemo,useState}from"react";
import{ArrowLeft,CheckCircle2,CircleHelp,Clock3,MapPin,Package,XCircle}from"lucide-react";
import{customerApi}from"./api.js";import{removeTrackedOrder}from"./trackedOrders.js";import{money}from"../format.js";
const labels={received:"Commande reçue",confirmed:"Confirmée",preparing:"En préparation",ready:"Prête",assigned:"Livreur assigné",out_for_delivery:"En livraison",delivered:"Livrée",cancelled:"Annulée"};
const reasons={out_of_stock:"Produit indisponible",unreachable:"Nous n'avons pas pu vous joindre",outside_zone:"Livraison impossible dans votre zone",closed:"Nous sommes fermés actuellement",other:"Autre raison"};
function pay(o){if(o.paymentStatus==="paid")return"Payée";if(o.paymentStatus==="failed")return"Paiement échoué";if(o.paymentMethod==="cash")return o.fulfillment==="pickup"?"À payer à la remise":"À payer à la livraison";return"Paiement en attente";}
export default function TrackingScreen({order,onHome}){
 const[id]=useState(order?.id),[token]=useState(order?.trackingToken||order?.token),[data,setData]=useState(null),[state,setState]=useState("loading"),[message,setMessage]=useState(""),[cancelOpen,setCancelOpen]=useState(false),[cancelling,setCancelling]=useState(false);
 const load=useCallback(async()=>{if(!id||!token){setState("error");setMessage("Le suivi de cette commande n'est pas disponible.");return false;}const r=await customerApi("/api/orders/track?id="+encodeURIComponent(id)+"&token="+encodeURIComponent(token));if(r.status===404){removeTrackedOrder(id);setState("error");setMessage("Le suivi de cette commande n'est plus disponible.");return "not_found";}if(!r.ok){setState("error");setMessage(r.status===0?"Connexion impossible. Nous réessaierons.":"Impossible de charger le suivi.");return false;}const next=r.data?.data||null;setData(next);setState("ready");setMessage("");return next?.status||null;},[id,token]);
 useEffect(()=>{let alive=true,timer=null;const tick=()=>{if(!alive||document.visibilityState!=="visible")return;load().then(status=>{if(alive&&status&&status!=="not_found"&&!["delivered","cancelled"].includes(status))timer=setTimeout(tick,15000);else if(alive&&!status)timer=setTimeout(tick,30000);});};load().then(status=>{if(alive&&document.visibilityState==="visible"&&status!=="not_found"&&!["delivered","cancelled"].includes(status))timer=setTimeout(tick,status?15000:30000);});const vis=()=>{clearTimeout(timer);if(document.visibilityState==="visible")load();};document.addEventListener("visibilitychange",vis);return()=>{alive=false;clearTimeout(timer);document.removeEventListener("visibilitychange",vis);};},[load]);
 async function cancel(){setCancelling(true);const r=await customerApi("/api/orders/cancel",{method:"POST",body:{id,token}});setCancelling(false);if(r.error==="not_cancellable"){setCancelOpen(false);setMessage("Cette commande ne peut plus être annulée.");return;}if(!r.ok){setMessage("L'annulation n'a pas pu être enregistrée.");return;}setCancelOpen(false);await load();}
 const timeline=useMemo(()=>{if(!data)return[];const a=["received","confirmed","preparing","ready",...(data.fulfillment==="delivery"?["assigned","out_for_delivery"]:[]),"delivered"],i=a.indexOf(data.status);return a.map(s=>({s,done:i>=0&&a.indexOf(s)<=i,active:s===data.status}));},[data]);
 if(state==="loading")return <div className="stack"><div className="page-head"><button className="back"onClick={onHome}><ArrowLeft size={20}/></button><h1>Suivi</h1></div><div className="empty"role="status"aria-live="polite"><Clock3 size={28}/><h3>Chargement du suivi…</h3></div></div>;
 if(state==="error")return <div className="stack"><div className="page-head"><button className="back"onClick={onHome}><ArrowLeft size={20}/></button><h1>Suivi</h1></div><div className="empty"role="alert"aria-live="polite"><CircleHelp size={28}/><h3>{message}</h3></div></div>;
 const cancelled=data.status==="cancelled";
 return <div className="stack"><div className="page-head"><button className="back"onClick={onHome}><ArrowLeft size={20}/></button><div><span className="eyebrow">Commande {data.id}</span><h1>{labels[data.status]||data.status}</h1></div></div>
 <section className="order-card"><div className="order-top"><b>{data.id}</b><span className="status green">{labels[data.status]||data.status}</span></div><p>{data.fulfillment==="pickup"?"Retrait sur place":"Livraison"} · {pay(data)}</p><div className="order-bottom"><strong>{money(data.total)}</strong><span>{data.createdAt?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(data.createdAt)):""}</span></div></section>
 {!cancelled&&<section className="card"><div className="section-head"><div><span className="eyebrow">Suivi en temps réel</span><h2>Votre commande avance</h2></div><MapPin size={20}/></div><div className="stack compact">{timeline.map(x=><div className={x.active?"setting active":x.done?"setting done":"setting"}key={x.s}><span className="avatar">{x.done?<CheckCircle2 size={18}/>:<Package size={18}/>}</span><div><b>{x.s==="ready"&&data.fulfillment==="pickup"?"Prête à retirer":x.s==="delivered"&&data.fulfillment==="pickup"?"Remise":labels[x.s]}</b></div></div>)}</div></section>}
 {cancelled&&<section className="card"role="status"><div className="section-head"><div><span className="eyebrow">Annulation</span><h2>Commande annulée</h2></div><XCircle size={22}/></div>{data.cancellation?.by==="customer"?<p>Vous avez annulé cette commande.</p>:<><p>{reasons[data.cancellation?.reason]||"Commande annulée."}</p>{data.cancellation?.note&&<p>{data.cancellation.note}</p>}</>}</section>}
 {message&&<div className="customer-error"role="alert"aria-live="polite">{message}</div>}
 {data.items?.length>0&&<section className="card"><div className="section-head"><div><span className="eyebrow">Détail</span><h2>Articles</h2></div></div>{data.items.map((x,i)=><div className="setting"key={i}><div><b>{x.quantity} × {x.name}</b></div></div>)}</section>}
 {!cancelled&&data.cancellable&&<button className="danger-button full"onClick={()=>setCancelOpen(true)}>Annuler ma commande</button>}
 {cancelOpen&&<div className="customer-modal-backdrop"><section className="customer-modal"role="dialog"aria-modal="true"><h2>Annuler ma commande ?</h2><p>Cette commande sera annulée.</p><div className="sub-actions"><button className="secondary"disabled={cancelling}onClick={()=>setCancelOpen(false)}>Garder la commande</button><button className="danger-button"disabled={cancelling}onClick={cancel}>{cancelling?"Annulation…":"Confirmer l'annulation"}</button></div></section></div>}</div>;
}
